### ISSUE TITLE
Please, include relationships examples

### ISSUE THREAD

**Issue by wellington1993** [frank06/ember-octane-blog#1]
I've followed the examples and shared your blog to all my friends.
But I need some examples of relationships.

I've followed: https://emberigniter.com/getting-started-ember-octane-tutorial/

But when I try to save a relationship in `createRecord` the data of the relation is sent blank.
Something related to promises.

Please see the screenshots, `laboratorio: {data: null}`: 

![imgpsh_fullsize_anim (2)](https://user-images.githubusercontent.com/6920053/78357399-f1ca3700-75a0-11ea-8372-372b7eefc046.png)

![imgpsh_fullsize_anim (3)](https://user-images.githubusercontent.com/6920053/78357396-f1ca3700-75a0-11ea-807e-c32bcc2bc719.png)
Can you help?
![imgpsh_fullsize_anim (4)](https://user-images.githubusercontent.com/6920053/78357395-f131a080-75a0-11ea-83fa-857a80396203.png)

Thanks!
![imgpsh_fullsize_anim (5)](https://user-images.githubusercontent.com/6920053/78357394-f0990a00-75a0-11ea-9578-c77da6a163e5.png)

![imgpsh_fullsize_anim (6)](https://user-images.githubusercontent.com/6920053/78357393-f0007380-75a0-11ea-9bd3-5c6a3d49cf00.png)

![imgpsh_fullsize_anim (8)](https://user-images.githubusercontent.com/6920053/78357391-ef67dd00-75a0-11ea-9e5c-e46cdfd63f6e.png)
![imgpsh_fullsize_anim (7)](https://user-images.githubusercontent.com/6920053/78357392-f0007380-75a0-11ea-86d4-767869766824.png)

![imgpsh_fullsize_anim (9)](https://user-images.githubusercontent.com/6920053/78357388-eecf4680-75a0-11ea-8869-79a96f20920e.png)

![imgpsh_fullsize_anim (10)](https://user-images.githubusercontent.com/6920053/78357387-ee36b000-75a0-11ea-8d95-ba2124bf93cf.png)

**Comment by wellington1993** [comment]
PS: In that example we are using JSON:API and Ruby on Rails 6 with `jsonapi-resources` gem.

Thanks!

**Comment by frank06** [comment]
It's not possible (unless the JSON:API spec allows it now?).

I wrote this a few years ago, for this same reason. Please note this article (and accompanying library) are *most definitely* outdated, but could give you an idea or two:

https://emberigniter.com/saving-models-relationships-json-api/
